### ISSUE TITLE
付録Bデータ内のDQ4とDQ7の見出しが逆になっている

### ISSUE THREAD

**Issue by yuilib** [showa-yojyo/dqbook#55]
https://showa-yojyo.github.io/dqbook/appendix_b.html

**Comment by showa-yojyo** [comment]
たいへん申し訳ない。今この投稿に気づきました。

リリース順 (DQ7 2000, DQ4 2001) に従って見出し順を決めました。したがって、現在のまま変更予定はありません。

**Comment by yuilib** [comment]
言葉が足りませんでした。
見出しの順序ではなく、見出しと内容が4と7で逆になっています。

例：PS版ドラクエ7にdq4_act.txtがリストされている

**Comment by showa-yojyo** [comment]
暑さで頭が回っていませんでした。なるほど DQ7 と DQ4 とでリストが逆でした。

対応します。ありがとうございます。
